ARG version=latest
FROM ubuntu:${version}
LABEL description = "This image is the shared base image for all other images in this repo. Please refer to README for usage"
LABEL source="https://github.com/dbenedic-insight/any-cloud-accelerators"
LABEL version="0.1"

ENTRYPOINT ["/bin/bash"]
